name: linex
summary: linex for line execution
description: linex for line execution
version: 0.0.2
grade: stable
base: core20

confinement: devmode

apps:
  linex:
    command: bin/linex
    plugs:
      - home

parts:
  linex:
    plugin: go
    source-type: git
    source: https://github.com/anandureghu/linex
