title: Linex
name: linex
summary: linex for line execution
description: linex for line execution
version: 0.0.3
grade: stable
base: core20

confinement: strict

apps:
  linex:
    command: bin/linex
    plugs:
      - home

parts:
  linex:
    plugin: go
    source-type: git
    source: https://github.com/anandureghu/linex

issues: https://github.com/anandureghu/linex/issues/new/choose
donation: https://paypal.me/anandureghu?country.x=IN&locale.x=en_GB

